# Generated by Django 3.2.4 on 2022-09-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='is_breakdown',
        ),
    ]
