# Generated by Django 3.2.4 on 2022-03-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='view_type',
            field=models.CharField(default='MA', max_length=10),
        ),
    ]
