# Generated by Django 3.2.4 on 2022-09-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0002_remove_request_is_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_breakdown',
            field=models.BooleanField(default=False),
        ),
    ]
