# Generated by Django 3.2.4 on 2022-03-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0002_employee_view_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='view_type',
            field=models.CharField(max_length=10),
        ),
    ]
