# Generated by Django 3.2.4 on 2022-09-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0003_request_is_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='breakdown_reason',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
