# Generated by Django 3.2.4 on 2022-03-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0003_alter_employee_view_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('mc_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mc_of', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=50)),
                ('register_no', models.CharField(max_length=50)),
                ('asset_no', models.CharField(max_length=50)),
                ('serial_no', models.CharField(max_length=50)),
                ('manufacture', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('plant', models.CharField(max_length=10)),
                ('power', models.CharField(max_length=50)),
                ('install_date', models.DateTimeField(null=True)),
                ('capacity', models.CharField(max_length=1000)),
                ('note', models.CharField(max_length=1000)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
