# Generated by Django 3.2.4 on 2022-10-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0004_request_breakdown_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='sap_mc_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
