# Generated by Django 3.2.4 on 2022-03-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0004_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='install_date',
            field=models.DateField(null=True),
        ),
    ]
