# Generated by Django 3.2.4 on 2022-03-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0005_alter_machine_install_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
