# Generated by Django 3.2.4 on 2022-03-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0006_machine_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='asset_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='capacity',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='manufacture',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='plant',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='power',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='register_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='serial_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
