# Generated by Django 3.2.4 on 2022-03-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0007_auto_20220305_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='section',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
