# Generated by Django 3.2.4 on 2022-03-06 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0010_request_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmsapp.employee'),
        ),
        migrations.AddField(
            model_name='member',
            name='emp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.employee'),
            preserve_default=False,
        ),
    ]
