# Generated by Django 3.2.4 on 2022-03-07 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0011_auto_20220306_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='emp',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmsapp.employee'),
        ),
        migrations.AlterField(
            model_name='member',
            name='emp',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.employee'),
        ),
    ]
