# Generated by Django 3.2.4 on 2022-03-07 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmsapp', '0012_auto_20220307_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='emp',
        ),
        migrations.RemoveField(
            model_name='member',
            name='emp',
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
