# Generated by Django 3.2.4 on 2022-03-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0017_alter_operatorworkingtime_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='finish_date',
            field=models.DateField(null=True),
        ),
    ]
