# Generated by Django 3.2.4 on 2022-03-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0018_request_finish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='finish_date',
        ),
        migrations.AddField(
            model_name='request',
            name='finish_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
