# Generated by Django 3.2.4 on 2022-03-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0019_auto_20220307_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_of',
            field=models.CharField(default='MA', max_length=10),
        ),
    ]
