# Generated by Django 3.2.4 on 2022-03-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0020_category_cat_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_of',
            field=models.CharField(max_length=10),
        ),
    ]
