# Generated by Django 3.2.4 on 2022-03-07 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0021_alter_category_cat_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineDowntime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(null=True)),
                ('stop_datetime', models.DateTimeField(null=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('mc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.machine')),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.request')),
            ],
        ),
    ]
