# Generated by Django 3.2.4 on 2022-03-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0024_auto_20220308_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='view_type',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='mc_of',
        ),
    ]
