# Generated by Django 3.2.4 on 2022-03-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0025_auto_20220308_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectiongroup',
            name='id',
        ),
        migrations.AlterField(
            model_name='sectiongroup',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
