# Generated by Django 3.2.4 on 2022-03-08 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0026_auto_20220308_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='req_to',
        ),
        migrations.AddField(
            model_name='request',
            name='section_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmsapp.sectiongroup'),
        ),
        migrations.AddField(
            model_name='sectiongroupmember',
            name='section_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cmsapp.sectiongroup'),
            preserve_default=False,
        ),
    ]
