# Generated by Django 3.2.4 on 2022-03-08 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0027_auto_20220308_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectiongroupmember',
            old_name='section_group',
            new_name='sg',
        ),
        migrations.RemoveField(
            model_name='request',
            name='section_group',
        ),
        migrations.AddField(
            model_name='request',
            name='sg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmsapp.sectiongroup'),
        ),
    ]
