# Generated by Django 3.2.4 on 2022-03-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0029_auto_20220308_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pv_created',
            field=models.CharField(default='Request Page', max_length=20),
        ),
    ]
