# Generated by Django 3.2.4 on 2022-03-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0030_employee_pv_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiongroup',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='SectionGroupMember',
        ),
    ]
