# Generated by Django 3.2.4 on 2022-03-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0033_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='capacity',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='note',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='request',
            name='reason',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='note',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
