# Generated by Django 3.2.4 on 2022-03-09 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0034_auto_20220309_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestVendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.request')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.vendor')),
            ],
        ),
    ]
