# Generated by Django 3.2.4 on 2022-03-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0035_requestvendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestvendor',
            old_name='vendor',
            new_name='ven',
        ),
    ]
