# Generated by Django 3.2.4 on 2022-03-09 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0036_rename_vendor_requestvendor_ven'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorWorkingTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(null=True)),
                ('stop_datetime', models.DateTimeField(null=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.request')),
                ('ven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.vendor')),
            ],
        ),
    ]
