# Generated by Django 3.2.4 on 2022-03-09 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0037_vendorworkingtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_cc', models.BooleanField(default=False)),
                ('email', models.CharField(max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('sg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.sectiongroup')),
            ],
        ),
    ]
