# Generated by Django 3.2.4 on 2022-03-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0038_mailgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='email',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
