# Generated by Django 3.2.4 on 2022-03-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0040_alter_request_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='email',
            field=models.CharField(default='-', max_length=20, null=True),
        ),
    ]
