# Generated by Django 3.2.4 on 2022-03-11 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0041_alter_request_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='email',
        ),
    ]
