# Generated by Django 3.2.4 on 2022-03-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0044_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('dv_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50, null=True)),
                ('serial_no', models.CharField(max_length=50, null=True)),
                ('manufacture', models.CharField(max_length=50, null=True)),
                ('model', models.CharField(max_length=50, null=True)),
                ('building', models.CharField(max_length=50, null=True)),
                ('floor', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('capacity', models.TextField(max_length=1000, null=True)),
                ('note', models.TextField(max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
