# Generated by Django 3.2.4 on 2022-03-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0045_device'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.AddField(
            model_name='machine',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
