# Generated by Django 3.2.4 on 2022-03-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0046_auto_20220312_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='location',
        ),
    ]
