# Generated by Django 3.2.4 on 2022-03-12 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0047_remove_machine_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmsapp.task'),
        ),
    ]
