# Generated by Django 3.2.4 on 2022-03-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0051_alter_mailgroup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='default_owt',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
