# Generated by Django 3.2.4 on 2022-03-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0052_employee_default_owt'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
