# Generated by Django 3.2.4 on 2022-03-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0053_file_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiongroup',
            name='line_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
