# Generated by Django 3.2.4 on 2022-04-02 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0055_machine_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='machine',
            name='group',
        ),
        migrations.AddField(
            model_name='machine',
            name='mcg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmsapp.machinegroup'),
        ),
    ]
