# Generated by Django 3.2.4 on 2022-04-02 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0056_auto_20220402_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalOperationTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=2)),
                ('time', models.CharField(max_length=20)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('mcg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.machinegroup')),
            ],
        ),
    ]
