# Generated by Django 3.2.4 on 2022-04-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0057_totaloperationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totaloperationtime',
            name='month',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='totaloperationtime',
            name='time',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='totaloperationtime',
            name='year',
            field=models.IntegerField(max_length=4),
        ),
    ]
