# Generated by Django 3.2.4 on 2022-05-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0058_auto_20220405_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='cause',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='corrective_action',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='spare_parts',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
