# Generated by Django 3.2.4 on 2022-04-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0058_auto_20220405_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totaloperationtime',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='totaloperationtime',
            name='time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='totaloperationtime',
            name='year',
            field=models.IntegerField(),
        ),
    ]
