# Generated by Django 3.2.4 on 2022-04-05 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0059_auto_20220405_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityObjectiveTarget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('type', models.CharField(max_length=4)),
                ('time', models.IntegerField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('mcg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.machinegroup')),
            ],
        ),
    ]
