# Generated by Django 3.2.4 on 2022-05-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0060_costing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalPart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mat_code', models.CharField(max_length=100, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('minimum', models.IntegerField(default=0)),
                ('note', models.TextField(max_length=1000, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SplindlePart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('machine', models.CharField(max_length=100, null=True)),
                ('model', models.CharField(max_length=100, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('register_date', models.DateField(null=True)),
                ('marker', models.CharField(max_length=100, null=True)),
                ('serial_no', models.CharField(max_length=100, null=True)),
                ('nose', models.CharField(max_length=100, null=True)),
                ('max_speed', models.CharField(max_length=100, null=True)),
                ('drive_type', models.CharField(max_length=100, null=True)),
                ('lubrication', models.CharField(max_length=100, null=True)),
                ('condition', models.CharField(max_length=100, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='machinegroup',
            name='downtime_est_hour',
            field=models.IntegerField(default=0),
        ),
    ]
