# Generated by Django 3.2.4 on 2022-05-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0060_costing'),
    ]

    operations = [
        migrations.AddField(
            model_name='costing',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
