# Generated by Django 3.2.4 on 2022-05-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0061_costing_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalPart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('mat_code', models.CharField(max_length=100, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=50, null=True)),
                ('minimum', models.IntegerField(default=0)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
