# Generated by Django 3.2.4 on 2022-05-14 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0061_auto_20220514_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinegroup',
            name='downtime_est_hour',
        ),
        migrations.CreateModel(
            name='EstimateWorkingTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('time', models.IntegerField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('mcg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.machinegroup')),
            ],
        ),
    ]
