# Generated by Django 3.2.4 on 2022-05-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0062_criticalpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='criticalpart',
            name='note',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
