# Generated by Django 3.2.4 on 2022-08-05 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0062_auto_20220514_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordStorage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('note', models.TextField(max_length=1000, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='qualityobjectivetarget',
            name='time',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='PasswordItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('pwst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.passwordstorage')),
            ],
        ),
    ]
