# Generated by Django 3.2.4 on 2022-08-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0063_auto_20220805_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='enable_pwst',
            field=models.BooleanField(default=False),
        ),
    ]
