# Generated by Django 3.2.4 on 2022-05-13 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0063_criticalpart_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criticalpart',
            name='type',
        ),
        migrations.RemoveField(
            model_name='criticalpart',
            name='unit',
        ),
    ]
