# Generated by Django 3.2.4 on 2022-05-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0065_splindlepart'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinegroup',
            name='downtime_hour',
            field=models.IntegerField(default=0),
        ),
    ]
