# Generated by Django 3.2.4 on 2022-05-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0066_machinegroup_downtime_hour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinegroup',
            old_name='downtime_hour',
            new_name='downtime_est_hour',
        ),
    ]
